### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by jamesnvc** [keyboardio/Kaleidoscope-LED-AlphaSquare#5]
- [x] Like LED Stalker, this sample code uses `USE_PLUGINS` - which is preferred, that or `Kaleidoscope.use`?
- [x] When the documentation says "one way or another, call the `display` method", what is it implying? How else could one call the display method?
- [ ] For references to rows & columns, it is unclear to me what those refer to - is row 0, column 0 the top-left key (`prog`, I guess?), bottom-left key, or something else?
- [x] What does it mean for a symbol to be drawn at a particular row & column? Is that where the top-left corner of the shape will be?
- [x] How do I pass in symbols to display? Is it an array of 16 values, a nested array of four four-element arrays, or something else?

**Comment by algernon** [comment]
* The preferred is `Kaleidoscope.use`. This is due to a recent change, and not all of the plugin docs have been updated yet.
* The "one way or the other" was meant to imply that one can call it from any place: from a macro, in `loop()`, via the `AlphaSquareEffect` LED effect, and so on.
* Yeeah. Physical ordering is keyboard-dependant, I would not want to document that here. But perhaps mentioning this, to look for the row/col stuff in the hardware library would be a good idea.
* Yep, at row/col means that's where the top-right corner of it will be.
* You can use a pre-defined symbol, a `Key` (which will use a pre-defined symbol, if there's one available), or you need to pass an `uint16_t`, which will be treated as a 4x4 map of bits. Each on-bit is a pixel to be drawn, while off-bits are transparent. The `SYM4x4` macro help creating these values.
